### ISSUE TITLE
Cell title as an empty string causes app to crash without a backtrace

### ISSUE THREAD

**Issue by andrewhavens** [clearsightstudio/ProMotion-form#42]
I ran into an issue that caused my app to crash...specifying a cell with only a title as an empty string:

```
  def form_data
    [{
      cells: [
        { title: '' }
      ]
    }]
  end
```

I'm not sure why this is causing it to crash. It also crashes with a nil title, but I think that's because [it's trying to default to the `:name`](https://github.com/clearsightstudio/ProMotion-form/blob/master/lib/ProMotion/form/form.rb#L71) which also hasn't been specified.

Not sure what the solution is to this, but I would be happy to submit a PR if you can give me some guidance on how we can support the use of an empty string.

**Comment by jamonholmgren** [comment]
Just saw this, @andrewhavens . 

Seems like FXForms is very finicky with nil and empty string values. We've been having a lot of issues with that.

Does a single space work?

**Comment by andrewhavens** [comment]
@jamonholmgren I just tried it and can confirm that a string with a single space (or multiple spaces) works.

**Comment by jamonholmgren** [comment]
It's pretty hacky, but we could check for `nil` or empty string and change to single space. Work for you?

**Comment by andrewhavens** [comment]
Yeah I think that would work.
